# Generated by Django 2.1.2 on 2018-10-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='author',
            new_name='user',
        ),
    ]
