# Generated by Django 2.1.2 on 2018-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20181005_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('category', models.TextField(default=None, max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
