# Generated by Django 2.1.2 on 2018-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20181006_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branches',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
