# Generated by Django 2.1.2 on 2018-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20181006_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezone',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
