# Generated by Django 2.1.2 on 2018-10-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20181009_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezone',
            name='contacts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Contacts'),
            preserve_default=False,
        ),
    ]
