# Generated by Django 2.1.2 on 2018-10-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_ezone_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezone',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contacts',
            name='ezone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Ezone'),
            preserve_default=False,
        ),
    ]
