# Generated by Django 2.1.2 on 2018-10-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20181009_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='ezone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Ezone'),
            preserve_default=False,
        ),
    ]
