# Generated by Django 2.1.2 on 2018-10-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20181009_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='atist',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
        migrations.AddField(
            model_name='track',
            name='track',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branches',
            name='ezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='rest.Ezone'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='rest.Ezone'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='rest.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.IntegerField(),
        ),
    ]
