# Generated by Django 2.1.2 on 2018-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20181018_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track',
        ),
        migrations.RemoveField(
            model_name='track',
            name='year',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
